ERROR_SPECIFICATION_FILE = -1
ERROR_MARKET_DATA_FILE = -2
ERROR_PARAMS_FILE = -3
ERROR_NETWORK_FILE = -4
ERROR_OPERATIONAL_DATA_FILE = -5
ERROR_NETWORK_MODEL = -6
ERROR_NETWORK_OPTIMIZATION = -7

BUS_PQ = 1
BUS_PV = 2
BUS_REF = 3
BUS_ISOLATED = 4

GEN_REFERENCE = 0
GEN_CONV = 1
GEN_RES_WIND = 2
GEN_RES_SOLAR = 3
GEN_RES_OTHER = 4
GEN_RES_CONTROLLABLE = 5
GEN_INTERCONNECTION = 6
GEN_CONTROLLABLE_TYPES = [GEN_REFERENCE, GEN_CONV, GEN_RES_CONTROLLABLE]
GEN_CURTAILLABLE_TYPES = [GEN_RES_WIND, GEN_RES_SOLAR, GEN_RES_OTHER, GEN_INTERCONNECTION]
GEN_RENEWABLE_TYPES = [GEN_RES_WIND, GEN_RES_SOLAR, GEN_RES_OTHER, GEN_RES_CONTROLLABLE]

BRANCH_UNKNOWN_RATING = 999.99
BRANCH_LIMIT_CURRENT = 1
BRANCH_LIMIT_APPARENT_POWER = 2
BRANCH_LIMIT_MIXED = 3
BRANCH_DEFAULT_ANGLE_MIN = -30.0  # degrees
BRANCH_DEFAULT_ANGLE_MAX = 30.0   # degrees
TRANSFORMER_MAXIMUM_RATIO = 1.17
TRANSFORMER_MINIMUM_RATIO = 0.83

ESS_MODEL_EXACT = 1
ESS_MODEL_BILINEAR_RELAXATION = 2
ESS_MODEL_POLYNOMIAL_COMPLEMENTARITY = 3

ENERGY_STORAGE_MAX_ENERGY_STORED = 0.90
ENERGY_STORAGE_MIN_ENERGY_STORED = 0.10
ENERGY_STORAGE_RELATIVE_INIT_SOC = 0.50

OBJ_MIN_COST = 1
OBJ_CONGESTION_MANAGEMENT = 2

COST_GENERATION_CURTAILMENT = 100.00
COST_CONSUMPTION_CURTAILMENT = 300.00
# Squared-voltage slack is approximately 2 * V * delta_V. At V ~= 1 p.u.,
# half the former component-slack coefficient preserves the first-order cost per delta_V.
PENALTY_VOLTAGE_SQUARED = 5e4
PENALTY_CURRENT = 1e3
PENALTY_NODE_BALANCE = 1e6
PENALTY_FLEXIBILITY = 1e3
PENALTY_GENERATION = 1e6
PENALTY_ESS = 1e6
PENALTY_ESS_BALANCE = 1e3
PENALTY_ESS_COMPLEMENTARITY = 1e2
PENALTY_SHARED_ESS = 1e6
PENALTY_SHARED_ESS_BALANCE = 1e3
PENALTY_GENERATION_CURTAILMENT = 1e0
PENALTY_LOAD_CURTAILMENT = 1e2
PENALTY_FLEXIBILITY_USAGE = 1e-2
PENALTY_ESS_USAGE = 1e-1
PENALTY_ESSO_SLACK = 1e3
PENALTY_SCENARIO_DEVIATION = 9e4
PENALTY_SHARED_ESS_SCENARIO_DEVIATION = 1e4
PENALTY_REGULARIZATION = 1e4
PENALTY_SETTLEMENT = 1e6

VMAG_VIOLATION_ALLOWED = 0.05   # Over/undervoltage allowed, ratio (±5%)
SIJ_VIOLATION_ALLOWED = 0.50    # Branch power flow violation allowed, ratio (+50%)
NODE_BALANCE_SLACK_LIMIT = 1e-4 # Node balance slacks' limit

DATA_ACTIVE_POWER = 1
DATA_REACTIVE_POWER = 2
DATA_UPWARD_FLEXIBILITY = 3
DATA_DOWNWARD_FLEXIBILITY = 4
DATA_COST_FLEXIBILITY = 5

EQUALITY_TOLERANCE = 1e-5
SMALL_TOLERANCE = 1e-4
ESS_COMPLEMENTARITY_TOLERANCE = SMALL_TOLERANCE
SHARED_ESS_ZERO_CAPACITY_TOLERANCE = 1e-10
SHARED_ESS_SNET_DEF_SAFE_KAPPA = 1.0       # finite kappa placeholder for sess_snet_def when shared-ESS capacity is (near-)zero; the row is deactivated in that regime, so this value never affects the solved feasible set
VIOLATION_TOLERANCE = 1e-3
EXPECTED_VALUE_PENALTY = 1e3
BENDERS_FEASIBILITY_TOLERANCE = 1e-3
